apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My automation
on:
  push:
    branches:
      - "**"
jobs:
  test-actions:
    environment: development
    steps:
      - uses: cloudbees-io/checkout@v1
        name: checkout
        with:
          provider: github
          repository: Poseidon1979/simple-java-maven-app
          ref: master
          token: ${{secrets.PYANG_GITHUB_TOKEN}}
          path: ./simple_java_app/
          github-server-url: https://github.com
      - uses: cloudbees-pyang/platform-action-maven@v0.2
        name: build
        with:
          project-folder: ./simple_java_app/
      - uses: docker://alpine:latest
        run: |
          ls ./simple_java_app/target/
      - name: Upload file to JFrog Artifactory
        uses: https://github.com/cloudbees-io/jfrog-artifactory-upload-file@v1
        with:
          url: ${{ vars.JFROG_URL }}
          #username: ${{ secrets.JFROG_USERNAME }}
          #password: ${{ secrets.JFROG_PASSWORD }}
          token: ${{ secrets.JFROG_TOKEN }}
          file-path: ./simple_java_app/target/my-app-1.0-SNAPSHOT.jar
          artifactory-path: artifactory/aop-cicd-kotlin/my-app-1.0.tar
